name: Relient CI-Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      #-> Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      #-> Install Bun
      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash 
          echo "$HOME/.bun/bin" >> $GITHUB_PATH

      #-> Install dependencies
      - name: Install Dependencies
        run: bun install

      #-> Generate Prisma Client
      - name: Generate Prisma Client
        run: |
          cd ./packages/db/postgres
          bunx prisma generate
    
      - name: Build the Project
        run: bun run build
